### PR TITLE
Hardcode table and remove build script

### PR DESCRIPTION
**Pull request by jorickert**
This also remove the build dependencies

### CODE REVIEW

**Comment by nlfiedler** [comment]
Thank you for the suggestion. I appreciate the effort, and the build is certainly faster as a result. However, this is in direct opposition to my intention of having the values computed versus a table of "magic numbers". I had hoped that the comment in the build script made that obvious, but it seems it was not clear. I'll address that.

**Comment by jorickert** [comment]
Couldn't the script used to generate the numbers be included in a comment or a separate tool ?

**Comment by nlfiedler** [comment]
May I ask what problem you are trying to solve?

**Comment by jorickert** [comment]
It's not really a problem, i was just looking at dependencies of a project and was a bit confused why this crate needs aes support. 
Not having some magic numbers is definitely a good approach, but having build time dependencies increases both build time and the number of crates needed to trust/review, which is why i would prefer it not to have them. But its your project so your decision

**Comment by nlfiedler** [comment]
All good points. My concern was that commented code is "dead" code; eventually it disappears from the code base. As for a separate tool, I don't know what that would look like in a standard Rust project. So keeping the code alive was paramount. However, since it really is nothing more than a sentence or two of explanation, I'll take your change, add an explanatory comment, and that will solve both issues.

**Comment by jorickert** [comment]
Thanks, something else that i did change was formatting the numbers as hex value for better formatting and readability, but this should not influence and functionality

**Comment by jorickert** [comment]
@nlfiedler It would be great if you could push the new version to crates.io

**Comment by nlfiedler** [comment]
Indeed, that would be a good idea, and it has been done.

**Pull request merged**
